apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-helm-operator
  namespace: flux
  labels:
    app: flux-helm-operator
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app: helm-operator
