---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: local-storage-provisioner
  namespace: kube-system
spec:
  releaseName: local-storage-provisioner
  chart:
    git: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner
    path: helm/provisioner
    ref: v2.3.3
  values:
    common:
      namespace: kube-system
      useNodeNameOnly: true
    classes:
    - name: local-scsi
      hostDir: "/mnt/disks"
      storageClass: true
