kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vitess-operator
  namespace: vitess
subjects:
- kind: ServiceAccount
  name: vitess-operator
roleRef:
  kind: Role
  name: vitess-operator
  apiGroup: rbac.authorization.k8s.io
