---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.27.0
  values:
    rbac:
      create: true
      pspEnabled: true

    meshProvider: istio
    metricsServer: http://prometheus-prometheus.monitoring.svc.cluster.local:9090

    podMonitor:
      enabled: true
