---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: system
spec:
  releaseName: external-dns
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: external-dns
    version: 2.14.3
  values:
    rbac: 
      create: true
      pspEnabled: true
      serviceAccountAnnotations: 
        iam.gke.io/gcp-service-account: external-dns@ck-gcp-training.iam.gserviceaccount.com
    provider: google

    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 200Mi         

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
