apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-vault-agent-injector
  namespace: consul
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: vault-agent-injector
  egress:
  # Apiserver
  - to:
    - ipBlock:
        cidr: 172.16.0.0/28
    ports:
    - protocol: TCP
      port: 443
  policyTypes:
  - Egress
