apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-vault
  namespace: consul
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: vault
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: vault
    ports:
    - protocol: TCP
      port: 8201

  - to:
    - podSelector:
        matchLabels:
          app: consul
    ports:
    - protocol: TCP
      port: 8500

  # GKE metadata server
  - to:
    - ipBlock:
        cidr: 127.0.0.1/32
    ports:
    - protocol: TCP
      port: 988

  # Internet for GCP APIs
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
    ports:
    - protocol: TCP
      port: 443
  policyTypes:
  - Egress
