---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: telegraf
  namespace: monitoring
spec:
  releaseName: telegraf
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: telegraf
    version: 1.1.9
  values: 
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 200Mi      

    config:
      inputs:
        - statsd:
            service_address: ":8125"
            percentiles:
              - 50
              - 95
              - 99
            metric_separator: "_"
            allowed_pending_messages: 10000
            percentile_limit: 1000
            parse_data_dog_tags: true
            delete_gauges: true
            delete_counters: true
            delete_sets: true
            delete_timings: true
