---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: system
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.12.0
  values:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: cert-manager@ck-gcp-training.iam.gserviceaccount.com

    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi

    prometheus:
      servicemonitor:
        enabled: true
