apiVersion: v1
kind: LimitRange
metadata:
  name: limit-container
  namespace: monitoring
spec:
  limits:
  - default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 10m
      memory: 32Mi
    type: Container
