apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vitesskeyspaces.vitess.io
spec:
  group: vitess.io
  names:
    kind: VitessKeyspace
    listKind: VitessKeyspaceList
    plural: vitesskeyspaces
    singular: vitesskeyspace
  scope: Namespaced
  version: v1alpha2
  subresources:
    status: {}
