apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vitesscells.vitess.io
spec:
  group: vitess.io
  names:
    kind: VitessCell
    listKind: VitessCellList
    plural: vitesscells
    singular: vitesscell
  scope: Namespaced
  version: v1alpha2
  subresources:
    status: {}
