apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus-vault-agent-config
  name: prometheus-vault-agent-config
  namespace: monitoring
data:
  config.hcl: |-
    vault = {
      address = "http://vault.consul.svc:8200"
    }
    
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "prometheus"
        }
      }

      sink "file" {
        config = {
          path = "/vault/secrets/.vault-token"
        }
      }
    }
