apiVersion: v1
kind: Service
metadata:
  name: linkerd
  namespace: system
  labels:
    app: linkerd
spec:
  selector:
    app: linkerd
  type: ClusterIP
  ports:
  - name: outgoing
    port: 4140
  - name: incoming
    port: 4141
  - name: admin
    port: 9990
