apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-flux
  namespace: flux
spec:
  podSelector: 
    matchLabels:
      app: flux
  ingress:
  - from:
    - ipBlock:
        cidr: 35.191.0.0/16
    - ipBlock:
        cidr: 130.211.0.0/22
    ports:
    - protocol: TCP
      port: 8080

  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
      podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 3030

  policyTypes:
  - Ingress
