apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-flux-helm-operator
  namespace: flux
spec:
  podSelector: 
    matchLabels:
      app: helm-operator
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
      podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 3030

  policyTypes:
  - Ingress
