apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-consul
  namespace: consul
spec:
  podSelector: 
    matchLabels:
      app: consul
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: consul
    ports:
    - protocol: TCP
      port: 8300
    - protocol: TCP
      port: 8301
    - protocol: UDP
      port: 8301

  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: vault

    - namespaceSelector:
        matchLabels:
          name: monitoring
      podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8500
  policyTypes:
  - Ingress
