apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-vault
  namespace: consul
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: vault
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: vault
    ports:
    - protocol: TCP
      port: 8201

  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
      podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8200
  policyTypes:
  - Ingress
