apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-all-to-kube-dns
  namespace: monitoring
spec:
  podSelector: {}
  egress:
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  policyTypes:
  - Egress
