apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-flux
  namespace: flux
spec:
  podSelector: 
    matchLabels:
      app: flux
  egress:
  # Apiserver
  - to:
    - ipBlock:
        cidr: 172.16.0.0/28
    ports:
    - protocol: TCP
      port: 443

  # GKE metadata server
  - to:
    - ipBlock:
        cidr: 127.0.0.1/32
    ports:
    - protocol: TCP
      port: 988

  # Internet for GCP APIs and github repository SSH access
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 22
  policyTypes:
  - Egress
