apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul-metrics
  name: consul-metrics
  namespace: consul
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8500
    targetPort: http
  selector:
    app: consul