apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-alertmanager
  namespace: monitoring
spec:
  podSelector: 
    matchLabels:
      app: alertmanager
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: alertmanager
    ports:
    - protocol: TCP
      port: 9094
    - protocol: UDP
      port: 9094

  - from:
    - namespaceSelector:
        matchLabels:
          name: system
      podSelector:
        matchLabels:
          app: traefik

    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 9093
  policyTypes:
  - Ingress
