apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-elasticsearch
  namespace: monitoring
spec:
  podSelector: 
    matchLabels:
      app: elasticsearch-master
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: elasticsearch-master
    ports:
    - protocol: TCP
      port: 9300

  - from:
    - podSelector:
        matchLabels:
          app: kibana
    - podSelector:
        matchLabels:
          app: filebeat-filebeat
    ports:
    - protocol: TCP
      port: 9200

  policyTypes:
  - Ingress
