apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-kube-state-metrics
  namespace: monitoring
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8080
  policyTypes:
  - Ingress
