apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-prometheus
  namespace: monitoring
spec:
  podSelector: 
    matchLabels:
      app: prometheus
  ingress:
  - from:
    - ipBlock:
        cidr: 35.191.0.0/16
    - ipBlock:
        cidr: 130.211.0.0/22
    - podSelector:
        matchLabels:
          app: prometheus
    - namespaceSelector:
        matchLabels:
          name: istio-system
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: flagger
    ports:
    - protocol: TCP
      port: 9090
  policyTypes:
  - Ingress
