apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-prometheus-operator
  namespace: monitoring
spec:
  podSelector: 
    matchLabels:
      app: prometheus-operator
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8080
  policyTypes:
  - Ingress
