apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: namerd
  namespace: system
  labels:
    app: namerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namerd
  template:
    metadata:
      labels:
        app: namerd
    spec:
      containers:
      - name: namerd
        image: buoyantio/namerd:1.4.6
        args:
        - /io.buoyant/namerd/config/config.yml
        ports:
        - name: thrift
          containerPort: 4100
        - name: http
          containerPort: 4180
        - name: mesh
          containerPort: 4321
        - name: admin
          containerPort: 9991
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: namerd
          mountPath: /io.buoyant/namerd/config
          readOnly: true
      - name: kubectl
        image: buoyantio/kubectl:v1.12.2
        args:
        - "proxy"
        - "-p"
        - "8001"
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      serviceAccount: namerd
      volumes:
      - name: namerd
        configMap:
          name: namerd
