apiVersion: v1
kind: Service
metadata:
  name: namerd
  namespace: system
  labels:
    app: namerd
spec:
  selector:
    app: namerd
  type: ClusterIP
  ports:
  - name: thrift
    port: 4100
  - name: http
    port: 4180
  - name: mesh
    port: 4321
  - name: admin
    port: 9991
