---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault
  namespace: consul
spec:
  releaseName: vault
  chart:
    git: https://github.com/hashicorp/vault-helm
    path: .
    ref: v0.3.2
  values:
    injector:
      enabled: true
    
    global:
      enabled: true
      
    server:
      image: 
        tag: 1.3.1
      annotations: |
        co.elastic.logs.vault/processors.1.decode_json_fields.fields.0: message
        co.elastic.logs.vault/processors.1.decode_json_fields.target: vault
        # Drop sys/metrics requests (prometheus scraping doesn't fill logs)
        co.elastic.logs.vault/processors.2.drop_event.when.equals.vault.request.path: sys/metrics
        # Drop request and data fields as they explode ES index.  Nb. data still retained in message field.
        co.elastic.logs.vault/processors.3.drop_fields.fields.0: vault.request.data
        co.elastic.logs.vault/processors.3.drop_fields.fields.1: vault.response.data
        com.charleswhrowe.elastic.index: vault
      serviceAccount:
        annotations: 
          iam.gke.io/gcp-service-account: vault-k8s@ck-gcp-training.iam.gserviceaccount.com
      authDelegator:
        enabled: true
      ha:
        enabled: true
        replicas: "3"
        config: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "consul" {
            path = "vault"
            address = "HOST_IP:8500"
          }
          seal "gcpckms" {
            project     = "ck-gcp-training"
            region      = "europe-west2"
            key_ring    = "vault-helm-unseal-kr"
            crypto_key  = "vault-helm-unseal-key"
          }

          telemetry {
            prometheus_retention_time = "10m"
            disable_hostname = true
          }

          log_format = "json"

      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 250m
    
    ui:
      enabled: true
